# Generated by Django 5.0.6 on 2024-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_chaivariety_delete_blogadding"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chaivariety",
            name="video",
            field=models.URLField(default=""),
        ),
    ]
