# Generated by Django 5.0.6 on 2024-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_chaivariety_description_chaivariety_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivariety",
            name="description",
            field=models.TextField(default=" "),
        ),
    ]
